apiVersion: v1
kind: Service
metadata:
  name: pihole-svc-tcp
spec:
  type: LoadBalancer
  #  loadBalancerIP: 192.168.1.230
  selector:
    app: pihole
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  - port: 53
    targetPort: dns-tcp
    protocol: TCP
    name: dns-tcp
