apiVersion: v1
kind: Service
metadata:
  name: pihole-svc-udp
spec:
  type: LoadBalancer
  #  loadBalancerIP: 192.168.1.230
  selector:
    app: pihole
  ports:
  - port: 53
    targetPort: dns-udp
    protocol: UDP
    name: dns-udp
